config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  # get 'posts/index'
  # get 'posts/new'
  # get 'posts/create'
  # get 'users/index'
  # get 'users/new'
  # get 'users/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  get "/u/:id", to: "users#profile", as: "user"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # #     
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]  
  before_action :authenticate_user!, except: %i[index show]  # %i creates an array of symbols

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: 'post was created successfully!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.save
      redirect_to post_path, notice: "Updated Successfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path, notice: "Post is successfully deleted!"
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class='post'>
    <h4><%= post.title %></h4>
    <% if current_user %>
        <small><b>Posted by: </b><%= link_to post.user.username, user_path(post.user) %></small>
    <% end %>
    <p><%= post.content %></p> 
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#Edit</h1>

<%= form_with model: @post, local: true do |form| %>
    <div id='main-form'>
        <%= form.label :title %>
        <%= form.text_field :title %> <br />

        <%= form.label :content %>
        <%= form.text_area :content %> <br />

        <%= form.submit%>
    </div>
<% end %>

<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
    <h1>Posts</h1>

    <% @posts.each do |post| %>
        <h4><%= post.id %></h4>
        <h4>Title : <%= post.title %></h4> 
        <p><%= post.content %></p> 
        <%= link_to 'Show this post', post_path(post) %>  

        <hr />
    <% end %>

    <%= link_to 'New Post', new_post_path%>



    <p>Find me in app/views/posts/index.html.erb</p>

</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= form_with model: @post, local: true do |form| %>
    <div id='main-form'>
        <%= form.label :title %>
        <%= form.text_field :title %> <br />

        <%= form.label :content %>
        <%= form.text_field :content %> <br />

        <%= form.submit%>
    </div>

<% end %>

app/views/posts/show.html.erb
<div class="container">

    <h3>Post#show</h3>

    <%= render @post %>

    <div>
        <% if current_user && current_user.id == @post.user_id %>
            <%= link_to 'Edit this post', edit_post_path(@post) %> |
        <% end %>
        <%= link_to 'Back to posts', posts_path %> <br />
        <% if current_user && current_user.id == @post.user_id %>
            <%= button_to 'Destroy this post', @post, method: :delete, class: "btn btn-primary" %>
        <% end %>
    </div>    
    <hr />
</div>

<div class="container">
    <h4>Comments</h4>
    <%= render 'comments/form', post: @post, comment: @post.comments.build, submit_label: 'Reply' %>
    <% @comments.each do |comment| %>
        <%= render 'comments/comment', post: @post, comment: comment %>
    <% end %>
</div>